Models/Producer.cs
namespace CosmeticsStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Producer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producer()
        {
            Products = new HashSet<Product>();
        }

        public int ProducerID { get; set; }

        [StringLength(100)]
        [DisplayName("Tên hãng")]
        [Required(ErrorMessage = "Vui lòng nhập trường này!")]
        public string Name { get; set; }

        [StringLength(250)]
        [DisplayName("Bí danh")]
        public string MetaTitle { get; set; }

        [DisplayName("Hiển thị")]
        public int? DisplayOder { get; set; }

        [StringLength(255)]
        [DisplayName("Thông tin")]
        [Required(ErrorMessage = "Vui lòng nhập trường này!")]
        public string Info { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập trường này!")]
        public string Logo { get; set; }

        [DisplayName("Trạng thái")]
        public bool? Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

Areas/Admin/Controllers/ProducersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CosmeticsStore.Models;

namespace CosmeticsStore.Areas.Admin.Controllers
{
    public class ProducersController : BaseController
    {
        private CosmeticsStoreDbContext db = new CosmeticsStoreDbContext();

        // GET: Admin/Producers
        public ActionResult Index()
        {
            return View(db.Producers.ToList());
        }

        // GET: Admin/Producers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producer producer = db.Producers.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        // GET: Admin/Producers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Producers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProducerID,Name,MetaTitle,DisplayOder,Info,Logo,Status")] Producer producer)
        {
            if (ModelState.IsValid)
            { 
                if(producer.Status == null)
                {
                    producer.Status = true;
                }
                producer.MetaTitle = Commons.ToUnsignString(producer.Name);
                db.Producers.Add(producer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(producer);
        }

        // GET: Admin/Producers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producer producer = db.Producers.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        // POST: Admin/Producers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProducerID,Name,MetaTitle,DisplayOder,Info,Logo,Status")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                if (producer.Status == null)
                {
                    producer.Status = true;
                }
                producer.MetaTitle = Commons.ToUnsignString(producer.Name);
                db.Entry(producer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producer);
        }

        // GET: Admin/Producers/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Producer producer = db.Producers.Find(id);
        //    if (producer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(producer);
        //}

        // POST: Admin/Producers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producer producer = db.Producers.Find(id);
            db.Producers.Remove(producer);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Producers/Create.cshtml
@model CosmeticsStore.Models.Producer

@{
    ViewBag.Title = "Thêm nhà cung cấp hãng chè";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section jsFooter{
    <script>
        $('#btnSelectLogo').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#Logo').val(url);
            };
            finder.popup();
        })
        var editor = CKEDITOR.replace('Content', {
            customConfig: '/Plugin/ckeditor/config.js',
        });
    </script>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h1 class="h3 mb-2 text-gray-800">Thêm hãng chè</h1>
            <div>
                <a href="/Admin/Producers/Index" class="btn btn-dark btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Trở lại</span>
                </a>
            </div>
        </div>
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DisplayOder, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DisplayOder, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DisplayOder, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Info, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Info, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Info, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" }})
                    <button class="btn-select-img" id="btnSelectLogo">...</button>
                    @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group2">
                <div class="text-center">
                    <button type="submit" class="btn btn-success btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-plus"></i>
                        </span>
                        <span class="text">Thêm mới</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
}

Areas/Admin/Views/Producers/Delete.cshtml
@model CosmeticsStore.Models.Producer

@{
    ViewBag.Title = "Xóa nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal fade show" style="display:block" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn có muốn xóa bản ghi này?</h5>
                    <a href="/Admin/Producers/Index" class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </a>
                </div>
                <div class="modal-footer">
                    <a href="/Admin/Producers/Index" class="btn btn-dark">
                        Trở lại
                    </a>
                    <button type="submit" class="btn btn-danger">
                        Xóa
                    </button>
                </div>
            </div>
        </div>
    </div>
}

Areas/Admin/Views/Producers/Details.cshtml
@model CosmeticsStore.Models.Producer

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h1 class="h3 mb-2 text-gray-800">Chi tiết nhà cung cấp</h1>
        <div>
            <a href="@Url.Action("Edit","Producers" , new { @id = Model.ProducerID})" class="btn btn-warning btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Thay đổi</span>
            </a>
        </div>
        <div>
            <a href="@Url.Action("Index","Contacts")" class="btn btn-dark btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-arrow-left"></i>
                </span>
                <span class="text">Trở lại</span>
            </a>
        </div>
    </div>
</div>

<p>
    @Html.DisplayNameFor(model => model.Name) : @Html.DisplayFor(model => model.Name)
</p>
<p>
    @Html.DisplayNameFor(model => model.MetaTitle) : @Html.DisplayFor(model => model.MetaTitle)
</p>
<p>
    @Html.DisplayNameFor(model => model.DisplayOder) : @Html.DisplayFor(model => model.DisplayOder)
</p>
<p>
    @Html.DisplayNameFor(model => model.Info) : @Html.DisplayFor(model => model.Info)
</p>
</p>
@Html.DisplayNameFor(model => model.Logo):<img  src="@Html.DisplayFor(model => model.Logo)" height="80" /> 
<p>
<p>
    @Html.DisplayNameFor(model => model.Status) : @Html.DisplayFor(model => model.Status)
</p>

Areas/Admin/Views/Producers/Edit.cshtml
@model CosmeticsStore.Models.Producer

@{
    ViewBag.Title = "Thêm hãng chè";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section jsFooter{
    <script>
        $('#btnSelectLogo').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#Logo').val(url);
            };
            finder.popup();
        })
        var editor = CKEDITOR.replace('Content', {
            customConfig: '/Plugin/ckeditor/config.js',
        });
    </script>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ProducerID)
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h1 class="h3 mb-2 text-gray-800">Cập nhật hãng chè</h1>
            <div>
                <a href="/Admin/Producers/Index" class="btn btn-dark btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Trở lại</span>
                </a>
            </div>
        </div>
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DisplayOder, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DisplayOder, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DisplayOder, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Info, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Info, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Info, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                    <button class="btn-select-img" id="btnSelectLogo">...</button>
                    @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group2">
                <div class="text-center">
                    <button type="submit" class="btn btn-warning btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-edit"></i>
                        </span>
                        <span class="text">Thay đổi</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
}

Areas/Admin/Views/Producers/Index.cshtml
@model IEnumerable<CosmeticsStore.Models.Producer>
@{
    var admin = Session["admin"] as CosmeticsStore.Models.Customer;
}
@{
    ViewBag.Title = "Danh sách hãng chè ";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h1 class="h3 mb-2 text-gray-800">Danh sách hãng chè</h1>
        <div>
            <a href="@Url.Action("Create","Producers")" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Thêm mới</span>
            </a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>


                        <th> @Html.DisplayNameFor(model => model.Name)</th>
                        <th> @Html.DisplayNameFor(model => model.DisplayOder)</th>
                        <th> @Html.DisplayNameFor(model => model.Info)</th>
                        <th> @Html.DisplayNameFor(model => model.Logo)</th>
                        <th> @Html.DisplayNameFor(model => model.Status)</th>

                        <th>Tác vụ</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DisplayOder)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Info)
                            </td>
                            <td>
                                <img src="@Html.DisplayFor(modelItem => item.Logo)" alt="Logo" height="50" />
                            </td>
                            <td>
                                @if (item.Status != false)
                                {
                                    <span>Đang bán</span>
                                }
                                else
                                {
                                    <span>Ngừng bán</span>

                                }
                            </td>
                            <td class="control">
                                <a href="@Url.Action("Edit","Producers" ,new { id=item.ProducerID})" title="Sửa" class="btn btn-warning btn-circle btn-sm"><i class="fas fa-edit"></i></a>
                                 <a href="@Url.Action("Delete", "Producers", new { id = item.ProducerID })" title="Xóa" class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>